// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeex_iCP0Vb0t1QxLScQcnW71zT-IiWf4',
    appId: '1:445583351304:web:c0f52580eb29ca0df67bbd',
    messagingSenderId: '445583351304',
    projectId: 'shoofi-b9bf8',
    authDomain: 'shoofi-b9bf8.firebaseapp.com',
    storageBucket: 'shoofi-b9bf8.firebasestorage.app',
    measurementId: 'G-EWFP1LJ7X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTApcVC1RyWrdCf8Wm9V6jpTHrJ7nAbvo',
    appId: '1:445583351304:android:c9607c0c8683b512f67bbd',
    messagingSenderId: '445583351304',
    projectId: 'shoofi-b9bf8',
    storageBucket: 'shoofi-b9bf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1gC4USKuKEs-VUWUy4tJxnU1jNbEHrEs',
    appId: '1:445583351304:ios:4a8d22a030862e98f67bbd',
    messagingSenderId: '445583351304',
    projectId: 'shoofi-b9bf8',
    storageBucket: 'shoofi-b9bf8.firebasestorage.app',
    iosBundleId: 'com.example.shooFi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1gC4USKuKEs-VUWUy4tJxnU1jNbEHrEs',
    appId: '1:445583351304:ios:4a8d22a030862e98f67bbd',
    messagingSenderId: '445583351304',
    projectId: 'shoofi-b9bf8',
    storageBucket: 'shoofi-b9bf8.firebasestorage.app',
    iosBundleId: 'com.example.shooFi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeex_iCP0Vb0t1QxLScQcnW71zT-IiWf4',
    appId: '1:445583351304:web:3c67dc19abaabdbcf67bbd',
    messagingSenderId: '445583351304',
    projectId: 'shoofi-b9bf8',
    authDomain: 'shoofi-b9bf8.firebaseapp.com',
    storageBucket: 'shoofi-b9bf8.firebasestorage.app',
    measurementId: 'G-EQL5H9XTER',
  );
}
